version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  backend:
    build: ./server
    ports:
      - "5500:5500"
    volumes:
      - ./server:/app
